version: "3"

services:

  {{ cookiecutter.project_slug }}_postgresql:
    image:
      postgres:14
    volumes:
      - {{ cookiecutter.project_slug }}_production_postgresql_volume:/var/lib/postgresql/data
    restart: always
    env_file: ../.envs/.env
    networks:
      - {{ cookiecutter.project_slug }}_production_postgres_network
  
  {{ cookiecutter.project_slug }}:
    image:
      {{ cookiecutter.docker_registry_url }}/{{ cookiecutter.project_slug }}:${BUILD_ID}
    entrypoint: ["/bin/sh", "/opt/{{ cookiecutter.project_slug }}/production.sh"]
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - {{ cookiecutter.project_slug }}_production_static_volume:/opt/{{ cookiecutter.project_slug }}/{{ cookiecutter.project_slug }}/static
      - {{ cookiecutter.project_slug }}_production_media_volume:/opt/{{ cookiecutter.project_slug }}/{{ cookiecutter.project_slug }}/media
    restart: on-failure
    networks:
      - {{ cookiecutter.project_slug }}_production_postgres_network
      - {{ cookiecutter.project_slug }}_production_redis_network
    depends_on:
      - {{ cookiecutter.project_slug }}_postgresql

volumes:
  {{ cookiecutter.project_slug }}_production_postgresql_volume:
    driver: local
    name: {{ cookiecutter.project_slug }}_production_postgresql_volume
  {{ cookiecutter.project_slug }}_production_static_volume:
    driver: local
    name: {{ cookiecutter.project_slug }}_production_static_volume
  {{ cookiecutter.project_slug }}_production_media_volume:
    driver: local
    name: {{ cookiecutter.project_slug }}_production_media_volume

networks:
  {{ cookiecutter.project_slug }}_production_postgres_network:
    driver: bridge
    name: {{ cookiecutter.project_slug }}_production_postgres_network
  {{ cookiecutter.project_slug }}_production_redis_network:
    driver: bridge
    name: {{ cookiecutter.project_slug }}_production_redis_network
